meditor:
  build: .
  environment:
   - identities=ldap
   - dbName=meditor
   - dbHost=meditorPostgres
   - dbPassword=meditor
   - oaiUrls=http://aleph.nkp.cz/OAI
   - oaiIdPrefixes="oai:aleph.nkp.cz:"
   - oaiBases=SKC,NKC
   - oaiRecordIdentifierLength=variable
   - fedoraHost=http://fedora/fedora
   - fedoraLogin=fedoraAdmin
   - fedoraPassword=fedoraAdmin
   - fedoraVersion=3.6.2
   - krameriusHost=http://kramerius/search/
   - krameriusLogin=krameriusAdmin
   - krameriusPassword=krameriusAdmin
   - imageServer.url=http://imageserver/
   - imageServer.known=/data/imageserver/
   - imageServer.unknown=/data/imageserver/meditor/
   - imageExtension=jpg, JPG, png, tiff, tif, jpeg, jp2, pdf
  ports:
    - "80:8080"
    - "443:8443"
  links:
    - meditorPostgres:meditorPostgres
    - ldap:ldap
meditorPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=meditor
    - POSTGRES_PASSWORD=meditor
    - POSTGRES_DB=meditor
  volumes:
    - /data/meditor/postgres:/var/lib/postgresql/data
  ports:
    - "5432:5432"
ldap:
  image: nickstenning/slapd
  environment:
    -  LDAP_DOMAIN=medit.mzk.cz
    -  LDAP_ORGANISATION="MZK"
    -  LDAP_ROOTPASS=s3cr3tpassw0rd
  volumes:
    - /data/meditor/ldap/etc:/etc/ldap/slapd.d
    - /data/meditor/ldap/ldap:/var/lib/ldap/
phpldapadmin:
  image: windfisch/phpldapadmin
  links:
    - ldap:ldap
  environment:
    -  LDAP_HOST=ldap
    -  LDAP_BASE_DN=dc=medit,dc=mzk,dc=cz
    -  LDAP_LOGIN_DN=cn=admin,dc=medit,dc=mzk,dc=cz
  ports:
    - "444:443"
